# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- feature/deploy-jar-to-nexus

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Revacom app image run
  jobs:
  - job: Build
    displayName: Build application
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Revacom front-end app
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
